import type { KeyType } from "./types";

const long = 40;

export const usKeys: { [key: string]: KeyType } = {
  AltLeft: { code: "AltLeft", length: long, name: "", shift: "" },
  AltRight: { code: "AltRight", length: long, name: "", shift: "" },
  Backquote: { code: "Backquote", name: "`", shift: "~" },
  Backslash: { code: "Backslash", length: 60, name: "\\", shift: "|" },
  Backspace: { code: "Backspace", name: "Backspace", shift: "Backspace" },
  BracketLeft: { code: "BracketLeft", name: "[", shift: "{" },
  BracketRight: { code: "BracketRight", name: "]", shift: "}" },
  CapsLock: { code: "CapsLock", length: 60, name: "", shift: "" },
  Comma: { code: "Comma", name: ",", shift: "<" },
  ControlLeft: { code: "ControlLeft", length: long, name: "", shift: "" },
  ControlRight: { code: "ControlRight", length: long, name: "", shift: "" },
  Delete: { code: "Delete", length: 85, name: "", shift: "" },
  Digit0: { code: "Digit0", name: "0", shift: ")" },
  Digit1: { code: "Digit1", name: "1", shift: "!" },
  Digit2: { code: "Digit2", name: "2", shift: "@" },
  Digit3: { code: "Digit3", name: "3", shift: "#" },
  Digit4: { code: "Digit4", name: "4", shift: "$" },
  Digit5: { code: "Digit5", name: "5", shift: "%" },
  Digit6: { code: "Digit6", name: "6", shift: "^" },
  Digit7: { code: "Digit7", name: "7", shift: "&" },
  Digit8: { code: "Digit8", name: "8", shift: "*" },
  Digit9: { code: "Digit9", name: "9", shift: "(" },
  Enter: { code: "Enter", length: 85, name: "Enter", shift: "Enter" },
  Equal: { code: "Equal", name: "=", shift: "+" },
  Escape: { code: "Escape", name: "es", shift: "es" },
  F1: { code: "F1", name: "F1", shift: "F1" },
  F10: { code: "F10", name: "F10", shift: "F10" },
  F11: { code: "F11", name: "F11", shift: "F11" },
  F12: { code: "F12", name: "F12", shift: "F12" },
  F2: { code: "F2", name: "F2", shift: "F2" },
  F3: { code: "F3", name: "F3", shift: "F3" },
  F4: { code: "F4", name: "F4", shift: "F4" },
  F5: { code: "F5", name: "F5", shift: "F5" },
  F6: { code: "F6", name: "F6", shift: "F6" },
  F7: { code: "F7", name: "F7", shift: "F7" },
  F8: { code: "F8", name: "F8", shift: "F8" },
  F9: { code: "F9", name: "F9", shift: "F9" },
  Fn: { code: "Fn", length: long, name: "", shift: "" },
  Key0: { code: "Key0", name: "0", shift: ")" },
  Key1: { code: "Key1", name: "1", shift: "!" },
  Key2: { code: "Key2", name: "2", shift: "@" },
  Key3: { code: "Key3", name: "3", shift: "#" },
  Key4: { code: "Key4", name: "4", shift: "$" },
  Key5: { code: "Key5", name: "5", shift: "%" },
  Key6: { code: "Key6", name: "6", shift: "^" },
  Key7: { code: "Key7", name: "7", shift: "&" },
  Key8: { code: "Key8", name: "8", shift: "*" },
  Key9: { code: "Key9", name: "9", shift: "(" },
  KeyA: { code: "KeyA", name: "a", shift: "A" },
  KeyB: { code: "KeyB", name: "b", shift: "B" },
  KeyC: { code: "KeyC", name: "c", shift: "C" },
  KeyD: { code: "KeyD", name: "d", shift: "D" },
  KeyE: { code: "KeyE", name: "e", shift: "E" },
  KeyF: { code: "KeyF", name: "f", shift: "F" },
  KeyG: { code: "KeyG", name: "g", shift: "G" },
  KeyH: { code: "KeyH", name: "h", shift: "H" },
  KeyI: { code: "KeyI", name: "i", shift: "I" },
  KeyJ: { code: "KeyJ", name: "j", shift: "J" },
  KeyK: { code: "KeyK", name: "k", shift: "K" },
  KeyL: { code: "KeyL", name: "l", shift: "L" },
  KeyM: { code: "KeyM", name: "m", shift: "M" },
  KeyN: { code: "KeyN", name: "n", shift: "N" },
  KeyO: { code: "KeyO", name: "o", shift: "O" },
  KeyP: { code: "KeyP", name: "p", shift: "P" },
  KeyQ: { code: "KeyQ", name: "q", shift: "Q" },
  KeyR: { code: "KeyR", name: "r", shift: "R" },
  KeyS: { code: "KeyS", name: "s", shift: "S" },
  KeyT: { code: "KeyT", name: "t", shift: "T" },
  KeyU: { code: "KeyU", name: "u", shift: "U" },
  KeyV: { code: "KeyV", name: "v", shift: "V" },
  KeyW: { code: "KeyW", name: "w", shift: "W" },
  KeyX: { code: "KeyX", name: "x", shift: "X" },
  KeyY: { code: "KeyY", name: "y", shift: "Y" },
  KeyZ: { code: "KeyZ", name: "z", shift: "Z" },
  MetaLeft: { code: "MetaLeft", length: long, name: "", shift: "" },
  MetaRight: { code: "MetaRight", length: long, name: "", shift: "" },
  Minus: { code: "Minus", name: "-", shift: "_" },
  Period: { code: "Period", name: ".", shift: ">" },
  Quote: { code: "Quote", name: "'", shift: '"' },
  ScrollLock: { code: "ScrollLock", name: "Scroll Lock", shift: "Scroll Lock" },
  Semicolon: { code: "Semicolon", name: ";", shift: ":" },
  ShiftLeft: { code: "ShiftLeft", length: 75, name: "Shift", shift: "Shift" },
  ShiftRight: {
    code: "ShiftRight",
    length: 105,
    name: "Shift",
    shift: "Shift"
  },
  Slash: { code: "Slash", name: "/", shift: "?" },
  Space: { code: "Space", length: 200, name: "", shift: "" },
  Tab: { code: "Tab", length: 50, name: "", shift: "" }
};

export const jisKeys: { [key: string]: KeyType } = {
  ArrowDown: { code: "ArrowDown", name: "Arrow Down", shift: "Arrow Down" },
  ArrowLeft: { code: "ArrowLeft", name: "Arrow Left", shift: "Arrow Left" },
  ArrowRight: { code: "ArrowRight", name: "Arrow Right", shift: "Arrow Right" },
  ArrowUp: { code: "ArrowUp", name: "Arrow Up", shift: "Arrow Up" },
  Backslash: { code: "Backslash", name: "\\", shift: "_" },
  Digit0: { code: "Digit0", name: "0", shift: "0" },
  Digit2: { code: "Digit2", name: "2", shift: '"' },
  Digit6: { code: "Digit6", name: "6", shift: "&" },
  Digit7: { code: "Digit7", name: "7", shift: "'" },
  Digit8: { code: "Digit8", name: "8", shift: "(" },
  Digit9: { code: "Digit9", name: "9", shift: ")" }
};
