export type RomanType = any;

const rawroman = [
  { char: "っうぁ", keys: ["wwha"] },
  { char: "っうぃ", keys: ["wwhi"] },
  { char: "っうぇ", keys: ["wwhe"] },
  { char: "っうぉ", keys: ["wwho"] },
  { char: "っヴぁ", keys: ["vva"] },
  { char: "っヴぃ", keys: ["vvi", "vvyi"] },
  { char: "っヴぇ", keys: ["vve", "vvye"] },
  { char: "っヴぉ", keys: ["vvo"] },
  { char: "っヴゃ", keys: ["vvya"] },
  { char: "っヴゅ", keys: ["vvyu"] },
  { char: "っヴょ", keys: ["vvyo"] },
  { char: "っきゃ", keys: ["kkya"] },
  { char: "っきぃ", keys: ["kkyi"] },
  { char: "っきゅ", keys: ["kkyu"] },
  { char: "っきぇ", keys: ["kkye"] },
  { char: "っきょ", keys: ["kkyo"] },
  { char: "っぎゃ", keys: ["ggya"] },
  { char: "っぎぃ", keys: ["ggyi"] },
  { char: "っぎゅ", keys: ["ggyu"] },
  { char: "っぎぇ", keys: ["ggye"] },
  { char: "っぎょ", keys: ["ggyo"] },
  { char: "っくぁ", keys: ["qqa", "qqwa"] },
  { char: "っくぃ", keys: ["qqi", "qqwi", "qqyi"] },
  { char: "っくぅ", keys: ["qqwu"] },
  { char: "っくぇ", keys: ["qqe", "qqwe", "qqye"] },
  { char: "っくぉ", keys: ["qqo", "qqwo"] },
  { char: "っくゃ", keys: ["qqya"] },
  { char: "っくゅ", keys: ["qqyu"] },
  { char: "っくょ", keys: ["qqyo"] },
  { char: "っぐぁ", keys: ["ggwa"] },
  { char: "っぐぃ", keys: ["ggwi"] },
  { char: "っぐぅ", keys: ["ggwu"] },
  { char: "っぐぇ", keys: ["ggwe"] },
  { char: "っぐぉ", keys: ["ggwo"] },
  { char: "っしゃ", keys: ["ssya", "ssha"] },
  { char: "っしぃ", keys: ["ssyi"] },
  { char: "っしゅ", keys: ["ssyu", "sshu"] },
  { char: "っしぇ", keys: ["ssye", "sshe"] },
  { char: "っしょ", keys: ["ssyo", "ssho"] },
  { char: "っじゃ", keys: ["jja", "jjya", "zzya"] },
  { char: "っじぃ", keys: ["jjyi", "zzyi"] },
  { char: "っじゅ", keys: ["jju", "jjyu", "zzyu"] },
  { char: "っじぇ", keys: ["jje", "jjye", "zzye"] },
  { char: "っじょ", keys: ["jjo", "jjyo", "zzyo"] },
  { char: "っすぁ", keys: ["sswa"] },
  { char: "っすぃ", keys: ["sswi"] },
  { char: "っすぅ", keys: ["sswu"] },
  { char: "っすぇ", keys: ["sswe"] },
  { char: "っすぉ", keys: ["sswo"] },
  { char: "っちゃ", keys: ["ttya", "ccha"] },
  { char: "っちぃ", keys: ["ttyi"] },
  { char: "っちゅ", keys: ["ttyu", "cchu", "ccyu"] },
  { char: "っちぇ", keys: ["ttye", "cche", "ccye"] },
  { char: "っちょ", keys: ["ttyo", "ccho", "ccyo"] },
  { char: "っぢゃ", keys: ["ddya"] },
  { char: "っぢぃ", keys: ["ddyi"] },
  { char: "っぢゅ", keys: ["ddyu"] },
  { char: "っぢぇ", keys: ["ddye"] },
  { char: "っぢょ", keys: ["ddyo"] },
  { char: "っつぁ", keys: ["ttsa"] },
  { char: "っつぃ", keys: ["ttsi"] },
  { char: "っつぇ", keys: ["ttse"] },
  { char: "っつぉ", keys: ["ttso"] },
  { char: "ってゃ", keys: ["ttha"] },
  { char: "ってぃ", keys: ["tthi"] },
  { char: "ってゅ", keys: ["tthu"] },
  { char: "ってぇ", keys: ["tthe"] },
  { char: "ってょ", keys: ["ttho"] },
  { char: "っでゃ", keys: ["ddha"] },
  { char: "っでぃ", keys: ["ddhi"] },
  { char: "っでゅ", keys: ["ddhu"] },
  { char: "っでぇ", keys: ["ddhe"] },
  { char: "っでょ", keys: ["ddho"] },
  { char: "っとぁ", keys: ["ttwa"] },
  { char: "っとぃ", keys: ["ttwi"] },
  { char: "っとぅ", keys: ["ttwu"] },
  { char: "っとぇ", keys: ["ttwe"] },
  { char: "っとぉ", keys: ["ttwo"] },
  { char: "っどぁ", keys: ["ddwa"] },
  { char: "っどぃ", keys: ["ddwi"] },
  { char: "っどぅ", keys: ["ddwu"] },
  { char: "っどぇ", keys: ["ddwe"] },
  { char: "っどぉ", keys: ["ddwo"] },
  { char: "っひゃ", keys: ["hhya"] },
  { char: "っひぃ", keys: ["hhyi"] },
  { char: "っひゅ", keys: ["hhyu"] },
  { char: "っひぇ", keys: ["hhye"] },
  { char: "っひょ", keys: ["hhyo"] },
  { char: "っびゃ", keys: ["bbya"] },
  { char: "っびぃ", keys: ["bbyi"] },
  { char: "っびゅ", keys: ["bbyu"] },
  { char: "っびぇ", keys: ["bbye"] },
  { char: "っびょ", keys: ["bbyo"] },
  { char: "っぴゃ", keys: ["ppya"] },
  { char: "っぴぃ", keys: ["ppyi"] },
  { char: "っぴゅ", keys: ["ppyu"] },
  { char: "っぴぇ", keys: ["ppye"] },
  { char: "っぴょ", keys: ["ppyo"] },
  { char: "っふぁ", keys: ["ffa", "ffwa"] },
  { char: "っふぃ", keys: ["ffi", "ffwi", "ffyi"] },
  { char: "っふぅ", keys: ["ffwu"] },
  { char: "っふぇ", keys: ["ffe", "ffwe", "ffye"] },
  { char: "っふぉ", keys: ["ffo", "ffwo"] },
  { char: "っふゃ", keys: ["ffya"] },
  { char: "っふゅ", keys: ["ffyu"] },
  { char: "っふょ", keys: ["ffyo"] },
  { char: "っみゃ", keys: ["mmya"] },
  { char: "っみぃ", keys: ["mmyi"] },
  { char: "っみゅ", keys: ["mmyu"] },
  { char: "っみぇ", keys: ["mmye"] },
  { char: "っみょ", keys: ["mmyo"] },
  { char: "っりゃ", keys: ["rrya"] },
  { char: "っりぃ", keys: ["rryi"] },
  { char: "っりゅ", keys: ["rryu"] },
  { char: "っりぇ", keys: ["rrye"] },
  { char: "っりょ", keys: ["rryo"] },

  // 二文字コード
  { char: "いぇ", keys: ["ye"] },
  { char: "うぁ", keys: ["wha"] },
  { char: "うぃ", keys: ["whi"] },
  { char: "うぇ", keys: ["whe"] },
  { char: "うぉ", keys: ["who"] },
  { char: "ヴぁ", keys: ["va"] },
  { char: "ヴぃ", keys: ["vi", "vyi"] },
  { char: "ヴぇ", keys: ["ve", "vye"] },
  { char: "ヴぉ", keys: ["vo"] },
  { char: "ヴゃ", keys: ["vya"] },
  { char: "ヴゅ", keys: ["vyu"] },
  { char: "ヴょ", keys: ["vyo"] },
  { char: "きゃ", keys: ["kya"] },
  { char: "きぃ", keys: ["kyi"] },
  { char: "きゅ", keys: ["kyu"] },
  { char: "きぇ", keys: ["kye"] },
  { char: "きょ", keys: ["kyo"] },
  { char: "ぎゃ", keys: ["gya"] },
  { char: "ぎぃ", keys: ["gyi"] },
  { char: "ぎゅ", keys: ["gyu"] },
  { char: "ぎぇ", keys: ["gye"] },
  { char: "ぎょ", keys: ["gyo"] },
  { char: "くぁ", keys: ["qa", "qwa"] },
  { char: "くぃ", keys: ["qi", "qwi", "qyi"] },
  { char: "くぅ", keys: ["qwu"] },
  { char: "くぇ", keys: ["qe", "qwe", "qye"] },
  { char: "くぉ", keys: ["qo", "qwo"] },
  { char: "くゃ", keys: ["qya"] },
  { char: "くゅ", keys: ["qyu"] },
  { char: "くょ", keys: ["qyo"] },
  { char: "ぐぁ", keys: ["gwa"] },
  { char: "ぐぃ", keys: ["gwi"] },
  { char: "ぐぅ", keys: ["gwu"] },
  { char: "ぐぇ", keys: ["gwe"] },
  { char: "ぐぉ", keys: ["gwo"] },
  { char: "しゃ", keys: ["sya", "sha"] },
  { char: "しぃ", keys: ["syi"] },
  { char: "しゅ", keys: ["syu", "shu"] },
  { char: "しぇ", keys: ["sye", "she"] },
  { char: "しょ", keys: ["syo", "sho"] },
  { char: "じゃ", keys: ["ja", "jya", "zya"] },
  { char: "じぃ", keys: ["jyi", "zyi"] },
  { char: "じゅ", keys: ["ju", "jyu", "zyu"] },
  { char: "じぇ", keys: ["je", "jye", "zye"] },
  { char: "じょ", keys: ["jo", "jyo", "zyo"] },
  { char: "すぁ", keys: ["swa"] },
  { char: "すぃ", keys: ["swi"] },
  { char: "すぅ", keys: ["swu"] },
  { char: "すぇ", keys: ["swe"] },
  { char: "すぉ", keys: ["swo"] },
  { char: "ちゃ", keys: ["tya", "cha"] },
  { char: "ちぃ", keys: ["tyi"] },
  { char: "ちゅ", keys: ["tyu", "chu", "cyu"] },
  { char: "ちぇ", keys: ["tye", "che", "cye"] },
  { char: "ちょ", keys: ["tyo", "cho", "cyo"] },
  { char: "ぢゃ", keys: ["dya"] },
  { char: "ぢぃ", keys: ["dyi"] },
  { char: "ぢゅ", keys: ["dyu"] },
  { char: "ぢぇ", keys: ["dye"] },
  { char: "ぢょ", keys: ["dyo"] },
  { char: "つぁ", keys: ["tsa"] },
  { char: "つぃ", keys: ["tsi"] },
  { char: "つぇ", keys: ["tse"] },
  { char: "つぉ", keys: ["tso"] },
  { char: "てゃ", keys: ["tha"] },
  { char: "てぃ", keys: ["thi"] },
  { char: "てゅ", keys: ["thu"] },
  { char: "てぇ", keys: ["the"] },
  { char: "てょ", keys: ["tho"] },
  { char: "でゃ", keys: ["dha"] },
  { char: "でぃ", keys: ["dhi"] },
  { char: "でゅ", keys: ["dhu"] },
  { char: "でぇ", keys: ["dhe"] },
  { char: "でょ", keys: ["dho"] },
  { char: "とぁ", keys: ["twa"] },
  { char: "とぃ", keys: ["twi"] },
  { char: "とぅ", keys: ["twu"] },
  { char: "とぇ", keys: ["twe"] },
  { char: "とぉ", keys: ["two"] },
  { char: "どぁ", keys: ["dwa"] },
  { char: "どぃ", keys: ["dwi"] },
  { char: "どぅ", keys: ["dwu"] },
  { char: "どぇ", keys: ["dwe"] },
  { char: "どぉ", keys: ["dwo"] },
  { char: "にゃ", keys: ["nya"] },
  { char: "にぃ", keys: ["nyi"] },
  { char: "にゅ", keys: ["nyu"] },
  { char: "にぇ", keys: ["nye"] },
  { char: "にょ", keys: ["nyo"] },
  { char: "ひゃ", keys: ["hya"] },
  { char: "ひぃ", keys: ["hyi"] },
  { char: "ひゅ", keys: ["hyu"] },
  { char: "ひぇ", keys: ["hye"] },
  { char: "ひょ", keys: ["hyo"] },
  { char: "びゃ", keys: ["bya"] },
  { char: "びぃ", keys: ["byi"] },
  { char: "びゅ", keys: ["byu"] },
  { char: "びぇ", keys: ["bye"] },
  { char: "びょ", keys: ["byo"] },
  { char: "ぴゃ", keys: ["pya"] },
  { char: "ぴぃ", keys: ["pyi"] },
  { char: "ぴゅ", keys: ["pyu"] },
  { char: "ぴぇ", keys: ["pye"] },
  { char: "ぴょ", keys: ["pyo"] },
  { char: "ふぁ", keys: ["fa", "fwa"] },
  { char: "ふぃ", keys: ["fi", "fwi", "fyi"] },
  { char: "ふぅ", keys: ["fwu"] },
  { char: "ふぇ", keys: ["fe", "fwe", "fye"] },
  { char: "ふぉ", keys: ["fo", "fwo"] },
  { char: "ふゃ", keys: ["fya"] },
  { char: "ふゅ", keys: ["fyu"] },
  { char: "ふょ", keys: ["fyo"] },
  { char: "みゃ", keys: ["mya"] },
  { char: "みぃ", keys: ["myi"] },
  { char: "みゅ", keys: ["myu"] },
  { char: "みぇ", keys: ["mye"] },
  { char: "みょ", keys: ["myo"] },
  { char: "りゃ", keys: ["rya"] },
  { char: "りぃ", keys: ["ryi"] },
  { char: "りゅ", keys: ["ryu"] },
  { char: "りぇ", keys: ["rye"] },
  { char: "りょ", keys: ["ryo"] },
  { char: "っか", keys: ["kka"] },
  { char: "っき", keys: ["kki"] },
  { char: "っく", keys: ["kku", "qqu"] },
  { char: "っけ", keys: ["kke"] },
  { char: "っこ", keys: ["kko"] },
  { char: "っが", keys: ["gga"] },
  { char: "っぎ", keys: ["ggi"] },
  { char: "っぐ", keys: ["ggu"] },
  { char: "っげ", keys: ["gge"] },
  { char: "っご", keys: ["ggo"] },
  { char: "っさ", keys: ["ssa"] },
  { char: "っし", keys: ["ssi", "sshi", "cci"] },
  { char: "っす", keys: ["ssu"] },
  { char: "っせ", keys: ["sse"] },
  { char: "っそ", keys: ["sso"] },
  { char: "っざ", keys: ["zza"] },
  { char: "っじ", keys: ["jji", "zzi"] },
  { char: "っず", keys: ["zzu"] },
  { char: "っぜ", keys: ["zze"] },
  { char: "っぞ", keys: ["zzo"] },
  { char: "った", keys: ["tta"] },
  { char: "っち", keys: ["tti", "cchi"] },
  { char: "っつ", keys: ["ttu", "ttsu"] },
  { char: "って", keys: ["tte"] },
  { char: "っと", keys: ["tto"] },
  { char: "っだ", keys: ["dda"] },
  { char: "っぢ", keys: ["ddi"] },
  { char: "っづ", keys: ["ddu"] },
  { char: "っで", keys: ["dde"] },
  { char: "っど", keys: ["ddo"] },
  { char: "っは", keys: ["hha"] },
  { char: "っひ", keys: ["hhi"] },
  { char: "っふ", keys: ["ffu", "hhu"] },
  { char: "っへ", keys: ["hhe"] },
  { char: "っぱ", keys: ["ppa"] },
  { char: "っぴ", keys: ["ppi"] },
  { char: "っぷ", keys: ["ppu"] },
  { char: "っぺ", keys: ["ppe"] },
  { char: "っぽ", keys: ["ppo"] },
  { char: "っば", keys: ["pba"] },
  { char: "っび", keys: ["pbi"] },
  { char: "っぶ", keys: ["pbu"] },
  { char: "っべ", keys: ["pbe"] },
  { char: "っぼ", keys: ["pbo"] },
  { char: "っほ", keys: ["hho"] },
  { char: "っま", keys: ["mma"] },
  { char: "っみ", keys: ["mmi"] },
  { char: "っむ", keys: ["mmu"] },
  { char: "っめ", keys: ["mme"] },
  { char: "っも", keys: ["mmo"] },
  { char: "っや", keys: ["yya"] },
  { char: "っゆ", keys: ["yyu"] },
  { char: "っよ", keys: ["yyo"] },
  { char: "っら", keys: ["rra"] },
  { char: "っり", keys: ["rri"] },
  { char: "っる", keys: ["rru"] },
  { char: "っれ", keys: ["rre"] },
  { char: "っろ", keys: ["rro"] },
  { char: "っわ", keys: ["wwa"] },
  { char: "っを", keys: ["wwo"] },

  // 一文字コード
  { char: "あ", keys: ["a"] },
  { char: "い", keys: ["i", "yi"] },
  { char: "う", keys: ["u", "whu", "wu"] },
  { char: "え", keys: ["e"] },
  { char: "お", keys: ["o"] },
  { char: "か", keys: ["ka", "ca"] },
  { char: "き", keys: ["ki"] },
  { char: "く", keys: ["ku", "cu", "qu"] },
  { char: "け", keys: ["ke"] },
  { char: "こ", keys: ["ko"] },
  { char: "さ", keys: ["sa"] },
  { char: "し", keys: ["si", "shi", "ci"] },
  { char: "す", keys: ["su"] },
  { char: "せ", keys: ["se"] },
  { char: "そ", keys: ["so"] },
  { char: "た", keys: ["ta"] },
  { char: "ち", keys: ["chi", "ti"] },
  { char: "つ", keys: ["tu", "tsu"] },
  { char: "て", keys: ["te"] },
  { char: "と", keys: ["to"] },
  { char: "な", keys: ["na"] },
  { char: "に", keys: ["ni"] },
  { char: "ぬ", keys: ["nu"] },
  { char: "ね", keys: ["ne"] },
  { char: "の", keys: ["no"] },
  { char: "は", keys: ["ha"] },
  { char: "ひ", keys: ["hi"] },
  { char: "ふ", keys: ["fu", "hu"] },
  { char: "へ", keys: ["he"] },
  { char: "ほ", keys: ["ho"] },
  { char: "ま", keys: ["ma"] },
  { char: "み", keys: ["mi"] },
  { char: "む", keys: ["mu"] },
  { char: "め", keys: ["me"] },
  { char: "も", keys: ["mo"] },
  { char: "や", keys: ["ya"] },
  { char: "ゆ", keys: ["yu"] },
  { char: "よ", keys: ["yo"] },
  { char: "ら", keys: ["ra"] },
  { char: "り", keys: ["ri"] },
  { char: "る", keys: ["ru"] },
  { char: "れ", keys: ["re"] },
  { char: "ろ", keys: ["ro"] },
  { char: "わ", keys: ["wa"] },
  { char: "を", keys: ["wo"] },
  { char: "ぁ", keys: ["la", "xa"] },
  { char: "ぃ", keys: ["li", "xi"] },
  { char: "ぅ", keys: ["lu", "xu"] },
  { char: "ぇ", keys: ["le", "xe"] },
  { char: "ぉ", keys: ["lo", "xo"] },
  { char: "ゃ", keys: ["lya", "xya"] },
  { char: "ゅ", keys: ["lyu", "xyu"] },
  { char: "ょ", keys: ["lyo", "xyo"] },
  { char: "ヵ", keys: ["lka", "xka"] },
  { char: "ヶ", keys: ["lke", "xke"] },
  { char: "っ", keys: ["ltu", "ltsu", "xtu", "xtsu"] },
  { char: "ゎ", keys: ["lwa", "xwa"] },
  { char: "が", keys: ["ga"] },
  { char: "ぎ", keys: ["gi"] },
  { char: "ぐ", keys: ["gu"] },
  { char: "げ", keys: ["ge"] },
  { char: "ご", keys: ["go"] },
  { char: "ざ", keys: ["za"] },
  { char: "じ", keys: ["ji", "zi"] },
  { char: "ず", keys: ["zu"] },
  { char: "ぜ", keys: ["ze"] },
  { char: "ぞ", keys: ["zo"] },
  { char: "だ", keys: ["da"] },
  { char: "ぢ", keys: ["di"] },
  { char: "づ", keys: ["du"] },
  { char: "で", keys: ["de"] },
  { char: "ど", keys: ["do"] },
  { char: "ば", keys: ["ba"] },
  { char: "び", keys: ["bi"] },
  { char: "ぶ", keys: ["bu"] },
  { char: "べ", keys: ["be"] },
  { char: "ぼ", keys: ["bo"] },
  { char: "ぱ", keys: ["pa"] },
  { char: "ぴ", keys: ["pi"] },
  { char: "ぷ", keys: ["pu"] },
  { char: "ぺ", keys: ["pe"] },
  { char: "ぽ", keys: ["po"] },
  { char: "ヴ", keys: ["vu"] },
  { char: "a", keys: ["a"] },
  { char: "b", keys: ["b"] },
  { char: "c", keys: ["c"] },
  { char: "d", keys: ["d"] },
  { char: "e", keys: ["e"] },
  { char: "f", keys: ["f"] },
  { char: "g", keys: ["g"] },
  { char: "h", keys: ["h"] },
  { char: "i", keys: ["i"] },
  { char: "j", keys: ["j"] },
  { char: "k", keys: ["k"] },
  { char: "l", keys: ["l"] },
  { char: "m", keys: ["m"] },
  { char: "n", keys: ["n"] },
  { char: "o", keys: ["o"] },
  { char: "p", keys: ["p"] },
  { char: "q", keys: ["q"] },
  { char: "r", keys: ["r"] },
  { char: "s", keys: ["s"] },
  { char: "t", keys: ["t"] },
  { char: "u", keys: ["u"] },
  { char: "v", keys: ["v"] },
  { char: "w", keys: ["w"] },
  { char: "x", keys: ["x"] },
  { char: "y", keys: ["y"] },
  { char: "z", keys: ["z"] },
  { char: "0", keys: ["0"] },
  { char: "1", keys: ["1"] },
  { char: "2", keys: ["2"] },
  { char: "3", keys: ["3"] },
  { char: "4", keys: ["4"] },
  { char: "5", keys: ["5"] },
  { char: "6", keys: ["6"] },
  { char: "7", keys: ["7"] },
  { char: "8", keys: ["8"] },
  { char: "9", keys: ["9"] },
  { char: "ー", keys: ["-"] },
  { char: "～", keys: ["-"] },
  { char: "、", keys: [","] },
  { char: "。", keys: ["."] },
  { char: "#", keys: ["#"] },
  { char: ";", keys: [";"] },
  { char: ":", keys: [":"] },
  { char: "(", keys: ["("] },
  { char: ")", keys: [")"] },
  { char: '"', keys: ['"'] },
  { char: "\\", keys: ["\\"] },
  { char: "\n", keys: ["\n"] },
  { char: "\t", keys: ["\t"] },
  { char: "\r", keys: ["\r"] },
  { char: "<", keys: ["<"] },
  { char: ">", keys: [">"] },
  { char: ",", keys: [","] },
  { char: ".", keys: ["."] },
  { char: "{", keys: ["{"] },
  { char: "}", keys: ["}"] },
  { char: "[", keys: ["["] },
  { char: "]", keys: ["]"] },
  { char: " ", keys: [" "] },
  { char: "=", keys: ["="] },
  { char: "%", keys: ["%"] },
  { char: "+", keys: ["+"] },
  { char: "-", keys: ["-"] },
  { char: "*", keys: ["*"] },
  { char: "/", keys: ["/"] },
  { char: "_", keys: ["_"] },
  { char: "^", keys: ["^"] },
  { char: "~", keys: ["~"] },
  { char: "!", keys: ["!"] },
  { char: "&", keys: ["&"] },
  { char: "'", keys: ["'"] },
  { char: "|", keys: ["|"] },
  { char: "@", keys: ["@"] },
  { char: "`", keys: ["`"] },
  { char: "?", keys: ["?"] }
];

const romans = {
  "\t": ["\t"],
  "\n": ["\n"],
  "\r": ["\r"],
  " ": [" "],
  "!": ["!"],
  '"': ['"'],
  "#": ["#"],
  "%": ["%"],
  "&": ["&"],
  "'": ["'"],
  "(": ["("],
  ")": [")"],
  "*": ["*"],
  "+": ["+"],
  ",": [","],
  "-": ["-"],
  ".": ["."],
  "/": ["/"],
  "0": ["0"],
  "1": ["1"],
  "2": ["2"],
  "3": ["3"],
  "4": ["4"],
  "5": ["5"],
  "6": ["6"],
  "7": ["7"],
  "8": ["8"],
  "9": ["9"],
  ":": [":"],
  ";": [";"],
  "<": ["<"],
  "=": ["="],
  ">": [">"],
  "?": ["?"],
  "@": ["@"],
  "[": ["["],
  "\\": ["\\"],
  "]": ["]"],
  "^": ["^"],
  _: ["_"],
  "`": ["`"],
  a: ["a"],
  b: ["b"],
  c: ["c"],
  d: ["d"],
  e: ["e"],
  f: ["f"],
  g: ["g"],
  h: ["h"],
  i: ["i"],
  j: ["j"],
  k: ["k"],
  l: ["l"],
  m: ["m"],
  n: ["n"],
  o: ["o"],
  p: ["p"],
  q: ["q"],
  r: ["r"],
  s: ["s"],
  t: ["t"],
  u: ["u"],
  v: ["v"],
  w: ["w"],
  x: ["x"],
  y: ["y"],
  z: ["z"],
  "{": ["{"],
  "|": ["|"],
  "}": ["}"],
  "~": ["~"],
  "、": [","],
  "。": ["."],
  ぁ: ["la", "xa"],
  あ: ["a"],
  ぃ: ["li", "xi"],
  い: ["i", "yi"],
  いぇ: ["ye"],
  ぅ: ["lu", "xu"],
  う: ["u", "whu", "wu"],
  うぁ: ["wha"],
  うぃ: ["whi"],
  うぇ: ["whe"],
  うぉ: ["who"],
  ぇ: ["le", "xe"],
  え: ["e"],
  ぉ: ["lo", "xo"],
  お: ["o"],
  か: ["ka", "ca"],
  が: ["ga"],
  き: ["ki"],
  きぃ: ["kyi"],
  きぇ: ["kye"],
  きゃ: ["kya"],
  きゅ: ["kyu"],
  きょ: ["kyo"],
  ぎ: ["gi"],
  ぎぃ: ["gyi"],
  ぎぇ: ["gye"],
  ぎゃ: ["gya"],
  ぎゅ: ["gyu"],
  ぎょ: ["gyo"],
  く: ["ku", "cu", "qu"],
  くぁ: ["qa", "qwa"],
  くぃ: ["qi", "qwi", "qyi"],
  くぅ: ["qwu"],
  くぇ: ["qe", "qwe", "qye"],
  くぉ: ["qo", "qwo"],
  くゃ: ["qya"],
  くゅ: ["qyu"],
  くょ: ["qyo"],
  ぐ: ["gu"],
  ぐぁ: ["gwa"],
  ぐぃ: ["gwi"],
  ぐぅ: ["gwu"],
  ぐぇ: ["gwe"],
  ぐぉ: ["gwo"],
  け: ["ke"],
  げ: ["ge"],
  こ: ["ko"],
  ご: ["go"],
  さ: ["sa"],
  ざ: ["za"],
  し: ["si", "shi", "ci"],
  しぃ: ["syi"],
  しぇ: ["sye", "she"],
  しゃ: ["sya", "sha"],
  しゅ: ["syu", "shu"],
  しょ: ["syo", "sho"],
  じ: ["ji", "zi"],
  じぃ: ["jyi", "zyi"],
  じぇ: ["je", "jye", "zye"],
  じゃ: ["ja", "jya", "zya"],
  じゅ: ["ju", "jyu", "zyu"],
  じょ: ["jo", "jyo", "zyo"],
  す: ["su"],
  すぁ: ["swa"],
  すぃ: ["swi"],
  すぅ: ["swu"],
  すぇ: ["swe"],
  すぉ: ["swo"],
  ず: ["zu"],
  せ: ["se"],
  ぜ: ["ze"],
  そ: ["so"],
  ぞ: ["zo"],
  た: ["ta"],
  だ: ["da"],
  ち: ["chi", "ti"],
  ちぃ: ["tyi"],
  ちぇ: ["tye", "che", "cye"],
  ちゃ: ["tya", "cha"],
  ちゅ: ["tyu", "chu", "cyu"],
  ちょ: ["tyo", "cho", "cyo"],
  ぢ: ["di"],
  ぢぃ: ["dyi"],
  ぢぇ: ["dye"],
  ぢゃ: ["dya"],
  ぢゅ: ["dyu"],
  ぢょ: ["dyo"],
  っ: ["ltu", "ltsu", "xtu", "xtsu"],
  っうぁ: ["wwha"],
  っうぃ: ["wwhi", "wwi"],
  っうぇ: ["wwhe", "wwe"],
  っうぉ: ["wwho"],
  っか: ["kka"],
  っが: ["gga"],
  っき: ["kki"],
  っきぃ: ["kkyi"],
  っきぇ: ["kkye"],
  っきゃ: ["kkya"],
  っきゅ: ["kkyu"],
  っきょ: ["kkyo"],
  っぎ: ["ggi"],
  っぎぃ: ["ggyi"],
  っぎぇ: ["ggye"],
  っぎゃ: ["ggya"],
  っぎゅ: ["ggyu"],
  っぎょ: ["ggyo"],
  っく: ["kku", "qqu"],
  っくぁ: ["qqa", "qqwa"],
  っくぃ: ["qqi", "qqwi", "qqyi"],
  っくぅ: ["qqwu"],
  っくぇ: ["qqe", "qqwe", "qqye"],
  っくぉ: ["qqo", "qqwo"],
  っくゃ: ["qqya"],
  っくゅ: ["qqyu"],
  っくょ: ["qqyo"],
  っぐ: ["ggu"],
  っぐぁ: ["ggwa"],
  っぐぃ: ["ggwi"],
  っぐぅ: ["ggwu"],
  っぐぇ: ["ggwe"],
  っぐぉ: ["ggwo"],
  っけ: ["kke"],
  っげ: ["gge"],
  っこ: ["kko"],
  っご: ["ggo"],
  っさ: ["ssa"],
  っざ: ["zza"],
  っし: ["ssi", "sshi", "cci"],
  っしぃ: ["ssyi"],
  っしぇ: ["ssye", "sshe"],
  っしゃ: ["ssya", "ssha"],
  っしゅ: ["ssyu", "sshu"],
  っしょ: ["ssyo", "ssho"],
  っじ: ["jji", "zzi"],
  っじぃ: ["jjyi", "zzyi"],
  っじぇ: ["jje", "jjye", "zzye"],
  っじゃ: ["jja", "jjya", "zzya"],
  っじゅ: ["jju", "jjyu", "zzyu"],
  っじょ: ["jjo", "jjyo", "zzyo"],
  っす: ["ssu"],
  っすぁ: ["sswa"],
  っすぃ: ["sswi"],
  っすぅ: ["sswu"],
  っすぇ: ["sswe"],
  っすぉ: ["sswo"],
  っず: ["zzu"],
  っせ: ["sse"],
  っぜ: ["zze"],
  っそ: ["sso"],
  っぞ: ["zzo"],
  った: ["tta"],
  っだ: ["dda"],
  っち: ["tti", "cchi"],
  っちぃ: ["ttyi", "ccyi"],
  っちぇ: ["ttye", "cche", "ccye"],
  っちゃ: ["ttya", "ccha", "ccya"],
  っちゅ: ["ttyu", "cchu", "ccyu"],
  っちょ: ["ttyo", "ccho", "ccyo"],
  っぢ: ["ddi"],
  っぢぃ: ["ddyi"],
  っぢぇ: ["ddye"],
  っぢゃ: ["ddya"],
  っぢゅ: ["ddyu"],
  っぢょ: ["ddyo"],
  っつ: ["ttu", "ttsu"],
  っつぁ: ["ttsa"],
  っつぃ: ["ttsi"],
  っつぇ: ["ttse"],
  っつぉ: ["ttso"],
  っづ: ["ddu"],
  って: ["tte"],
  ってぃ: ["tthi"],
  ってぇ: ["tthe"],
  ってゃ: ["ttha"],
  ってゅ: ["tthu"],
  ってょ: ["ttho"],
  っで: ["dde"],
  っでぃ: ["ddhi"],
  っでぇ: ["ddhe"],
  っでゃ: ["ddha"],
  っでゅ: ["ddhu"],
  っでょ: ["ddho"],
  っと: ["tto"],
  っとぁ: ["ttwa"],
  っとぃ: ["ttwi"],
  っとぅ: ["ttwu"],
  っとぇ: ["ttwe"],
  っとぉ: ["ttwo"],
  っど: ["ddo"],
  っどぁ: ["ddwa"],
  っどぃ: ["ddwi"],
  っどぅ: ["ddwu"],
  っどぇ: ["ddwe"],
  っどぉ: ["ddwo"],
  っは: ["hha"],
  っば: ["pba"],
  っぱ: ["ppa"],
  っひ: ["hhi"],
  っひぃ: ["hhyi"],
  っひぇ: ["hhye"],
  っひゃ: ["hhya"],
  っひゅ: ["hhyu"],
  っひょ: ["hhyo"],
  っび: ["pbi"],
  っびぃ: ["bbyi"],
  っびぇ: ["bbye"],
  っびゃ: ["bbya"],
  っびゅ: ["bbyu"],
  っびょ: ["bbyo"],
  っぴ: ["ppi"],
  っぴぃ: ["ppyi"],
  っぴぇ: ["ppye"],
  っぴゃ: ["ppya"],
  っぴゅ: ["ppyu"],
  っぴょ: ["ppyo"],
  っふ: ["ffu", "hhu"],
  っふぁ: ["ffa", "ffwa"],
  っふぃ: ["ffi", "ffwi", "ffyi"],
  っふぅ: ["ffwu"],
  っふぇ: ["ffe", "ffwe", "ffye"],
  っふぉ: ["ffo", "ffwo"],
  っふゃ: ["ffya"],
  っふゅ: ["ffyu"],
  っふょ: ["ffyo"],
  っぶ: ["pbu"],
  っぷ: ["ppu"],
  っへ: ["hhe"],
  っべ: ["pbe"],
  っぺ: ["ppe"],
  っほ: ["hho"],
  っぼ: ["pbo"],
  っぽ: ["ppo"],
  っま: ["mma"],
  っみ: ["mmi"],
  っみぃ: ["mmyi"],
  っみぇ: ["mmye"],
  っみゃ: ["mmya"],
  っみゅ: ["mmyu"],
  っみょ: ["mmyo"],
  っむ: ["mmu"],
  っめ: ["mme"],
  っも: ["mmo"],
  っや: ["yya"],
  っゆ: ["yyu"],
  っよ: ["yyo"],
  っら: ["rra"],
  っり: ["rri"],
  っりぃ: ["rryi"],
  っりぇ: ["rrye"],
  っりゃ: ["rrya"],
  っりゅ: ["rryu"],
  っりょ: ["rryo"],
  っる: ["rru"],
  っれ: ["rre"],
  っろ: ["rro"],
  っわ: ["wwa"],
  っを: ["wwo"],
  っヴぁ: ["vva"],
  っヴぃ: ["vvi", "vvyi"],
  っヴぇ: ["vve", "vvye"],
  っヴぉ: ["vvo"],
  っヴゃ: ["vvya"],
  っヴゅ: ["vvyu"],
  っヴょ: ["vvyo"],
  つ: ["tu", "tsu"],
  つぁ: ["tsa"],
  つぃ: ["tsi"],
  つぇ: ["tse"],
  つぉ: ["tso"],
  づ: ["du"],
  て: ["te"],
  てぃ: ["thi"],
  てぇ: ["the"],
  てゃ: ["tha"],
  てゅ: ["thu"],
  てょ: ["tho"],
  で: ["de"],
  でぃ: ["dhi"],
  でぇ: ["dhe"],
  でゃ: ["dha"],
  でゅ: ["dhu"],
  でょ: ["dho"],
  と: ["to"],
  とぁ: ["twa"],
  とぃ: ["twi"],
  とぅ: ["twu"],
  とぇ: ["twe"],
  とぉ: ["two"],
  ど: ["do"],
  どぁ: ["dwa"],
  どぃ: ["dwi"],
  どぅ: ["dwu"],
  どぇ: ["dwe"],
  どぉ: ["dwo"],
  な: ["na"],
  に: ["ni"],
  にぃ: ["nyi"],
  にぇ: ["nye"],
  にゃ: ["nya"],
  にゅ: ["nyu"],
  にょ: ["nyo"],
  ぬ: ["nu"],
  ね: ["ne"],
  の: ["no"],
  は: ["ha"],
  ば: ["ba"],
  ぱ: ["pa"],
  ひ: ["hi"],
  ひぃ: ["hyi"],
  ひぇ: ["hye"],
  ひゃ: ["hya"],
  ひゅ: ["hyu"],
  ひょ: ["hyo"],
  び: ["bi"],
  びぃ: ["byi"],
  びぇ: ["bye"],
  びゃ: ["bya"],
  びゅ: ["byu"],
  びょ: ["byo"],
  ぴ: ["pi"],
  ぴぃ: ["pyi"],
  ぴぇ: ["pye"],
  ぴゃ: ["pya"],
  ぴゅ: ["pyu"],
  ぴょ: ["pyo"],
  ふ: ["fu", "hu"],
  ふぁ: ["fa", "fwa"],
  ふぃ: ["fi", "fwi", "fyi"],
  ふぅ: ["fwu"],
  ふぇ: ["fe", "fwe", "fye"],
  ふぉ: ["fo", "fwo"],
  ふゃ: ["fya"],
  ふゅ: ["fyu"],
  ふょ: ["fyo"],
  ぶ: ["bu"],
  ぷ: ["pu"],
  へ: ["he"],
  べ: ["be"],
  ぺ: ["pe"],
  ほ: ["ho"],
  ぼ: ["bo"],
  ぽ: ["po"],
  ま: ["ma"],
  み: ["mi"],
  みぃ: ["myi"],
  みぇ: ["mye"],
  みゃ: ["mya"],
  みゅ: ["myu"],
  みょ: ["myo"],
  む: ["mu"],
  め: ["me"],
  も: ["mo"],
  ゃ: ["lya", "xya"],
  や: ["ya"],
  ゅ: ["lyu", "xyu"],
  ゆ: ["yu"],
  ょ: ["lyo", "xyo"],
  よ: ["yo"],
  ら: ["ra"],
  り: ["ri"],
  りぃ: ["ryi"],
  りぇ: ["rye"],
  りゃ: ["rya"],
  りゅ: ["ryu"],
  りょ: ["ryo"],
  る: ["ru"],
  れ: ["re"],
  ろ: ["ro"],
  ゎ: ["lwa", "xwa"],
  わ: ["wa"],
  を: ["wo"],
  ヴ: ["vu"],
  ヴぁ: ["va"],
  ヴぃ: ["vi", "vyi"],
  ヴぇ: ["ve", "vye"],
  ヴぉ: ["vo"],
  ヴゃ: ["vya"],
  ヴゅ: ["vyu"],
  ヴょ: ["vyo"],
  ヵ: ["lka", "xka"],
  ヶ: ["lke", "xke"],
  ー: ["-"],
  "～": ["-"]
};

export function StrToRoman(value: string): RomanType {
  const roman: { [key: string]: string[] } = {};
  rawroman.forEach((roma) => {
    roman[roma.char] = roma.keys;
  });
  console.log(value, roman);
}

// export class Word {

// }
